project:
  type: book

book:
  title: "One-Shots"
  author: "James Salvatore"
  date: "12/27/2023"
  chapters:
  - part: "Snowbound"
    chapters:
    - index.qmd
    - ./snowbound/acts/act_1.qmd
    - ./snowbound/acts/act_2.qmd
    - ./snowbound/acts/act_3.qmd
    - ./snowbound/data/_reference.qmd
  sidebar:
    collapse-level: 1

# bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
  pdf:
    documentclass: scrreprt

# Themes I like:
# Light: lux, cosmo, cerulean, journal, lumen
# Dark: darkly, cyborg.

# TODO: Maybe figure out how to make lux into a dark theme...
# TODO: Lux doesn't allow for bold, etc., formatting.

